version: '3'
services:
  leave:
    image: "test"
    container_name: "test_test"
    ports:
      - "90:80"
    volumes:
      - ./config:/home/leave/nkp-leave-api/config
    restart: always
    networks:
      docker-network:
        ipv4_address: 192.168.1.11
  hello:
    image: "dockercloud/hello-world"
    container_name: "hello_test"
    ports:
      - "99:80"
    restart: always
    networks:
      docker-network:
        ipv4_address: 192.168.1.13
  nginx:
    image: "nginx"
    container_name: "ngin"
    ports:
      - "93:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      docker-network:
        ipv4_address: 192.168.1.10
networks:
  docker-network:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24